"""empty message

Revision ID: 349286d5d804
Revises: d1abd0f3f886
Create Date: 2022-05-30 14:21:52.745357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349286d5d804'
down_revision = 'd1abd0f3f886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.add_column('Venue', sa.Column('genres', sa.ARRAY(120)))
     op.add_column('Artist', sa.Column('genres', sa.ARRAY(120)))
    # ### end Alembic commands ###
