"""empty message

Revision ID: 62b1e08c1abc
Revises: 3eaf6d1374b1
Create Date: 2022-05-30 14:06:39.718171

"""
from tokenize import String
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b1e08c1abc'
down_revision = '3eaf6d1374b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres', sa.ARRAY(sa.String(120)))
    op.alter_column('Venue', 'genres', sa.ARRAY(sa.String(120)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',sa.ARRAY(sa.String(120)))
    op.alter_column('Venue', 'genres', sa.ARRAY(sa.String(120)))
    # ### end Alembic commands ###
