"""empty message

Revision ID: 6c7ab5b01e28
Revises: 349286d5d804
Create Date: 2022-05-30 14:23:28.059636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7ab5b01e28'
down_revision = '349286d5d804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String(120))))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String(120))))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
